### ISSUE TITLE
被墙了？

### ISSUE THREAD

**Issue by Xavier9896** [greenhandatsjtu/steins-gate-visitor-count#1]
不开代理加载不出来，似乎是被墙了？？？

**Comment by greenhandatsjtu** [comment]
抱歉，我才看到issue
我测试了下，不开代理访问不了 https://steins-gate-visitor-count.greenhandatsjtu.repl.co/xxx ，应该确实被屏蔽了。但 https://repl.co/ 还能正常访问，应该是只屏蔽了我的app😦

然后我fork了另一个app，网址是 https://steins-gate-counter.greenhandatsjtu.repl.co/ ，这个URL可以直连，使用方法和之前一致，修改一下前缀就行了，访问量也是一致的不用担心

不过如果是是用在GitHub上的话，不用更改，因为GitHub访问图片要经过它自己的缓存 https://camo.githubusercontent.com/ 我这里是直连缓存的

ps: 写到这的时候 https://steins-gate-visitor-count.greenhandatsjtu.repl.co/ 我这里也能直连了😂
